### ISSUE TITLE
Wrong folder name in Readme.md

### ISSUE THREAD

**Issue by tjedrak** [ItinerisLtd/trellis-purge-wp-rocket-cache-during-deploy#3]
Hi @TangRufus 
I noticed that when you install from ansible-galaxy you create different folder than it's in your description:

![Screenshot 2020-03-10 at 09 04 31](https://user-images.githubusercontent.com/5551518/76291923-6b2a7e80-62ae-11ea-97a1-8e6a221f9486.jpg)

```
fatal: [new.kryptokasyna.com]: FAILED! => {"reason": "Could not find or access '/Users/tomaszjedrak/Wordpress/kryptokasyna/trellis/vendor/roles/trellis-purge-wp-rocket-cache-during-deploy/tasks/main.yml' on the Ansible Controller."}
``` 

It's `purge-wp-rocket-cache`, and thanks for the tool, it's great :)

**Comment by tangrufus** [comment]
Can you show us your `galaxy.yml` please?

The directory name can be customized in `galaxy.yml`, example:

```yaml
- src: https://github.com/ItinerisLtd/trellis-purge-wp-rocket-cache-during-deploy
  version: x.y.z
  name: the-directory-name-anything-you-want
```
